# Generated by Django 3.2.20 on 2024-05-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('retornable', models.BooleanField(default=False)),
                ('tamaño_embalaje', models.PositiveIntegerField(default=1)),
                ('existencias', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
