# Generated by Django 4.2.7 on 2024-05-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0003_alter_productos_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default='productos/default.jpeg', upload_to='productos/'),
        ),
    ]
